fix: Use `.lines()` instead of `.split('\n')`
Should fix the issue of windows build panicking on boot.
The parse failed (most likely anyways) because there was a trailing `\r`
in the `y` value field. Note that you need to checkout tag `v0.1.0g` for
the code referenced below.

```
thread 'Compute Task Pool (3)' panicked at generate_world_collisions\src\serialization.rs:32:45:
failed to parse f32: ParseFloatError { kind: Invalid }
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Encountered a panic in system rantoni::world::map::parse_polygon_data!
Encountered a panic in system Pipe(bevy_state::state::transitions::last_transition<rantoni::GameState>, bevy_state::state::transitions::run_enter<rantoni::GameState>)!
Encountered a panic in system bevy_app::main_schedule::Main::run_main!
```